// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import confighelper "github.com/Chris-Greaves/stencil/confighelper"
import mock "github.com/stretchr/testify/mock"

// Config is an autogenerated mock type for the Config type
type Config struct {
	mock.Mock
}

// GetAllValues provides a mock function with given fields:
func (_m *Config) GetAllValues() ([]confighelper.Setting, error) {
	ret := _m.Called()

	var r0 []confighelper.Setting
	if rf, ok := ret.Get(0).(func() []confighelper.Setting); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]confighelper.Setting)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Object provides a mock function with given fields:
func (_m *Config) Object() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// SetValues provides a mock function with given fields: settings
func (_m *Config) SetValues(settings []confighelper.Setting) error {
	ret := _m.Called(settings)

	var r0 error
	if rf, ok := ret.Get(0).(func([]confighelper.Setting) error); ok {
		r0 = rf(settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
