// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import io "io"
import mock "github.com/stretchr/testify/mock"

// Engine is an autogenerated mock type for the Engine type
type Engine struct {
	mock.Mock
}

// ParseAndExecuteFile provides a mock function with given fields: sourcePath, settings, wr
func (_m *Engine) ParseAndExecuteFile(sourcePath string, settings interface{}, wr io.Writer) error {
	ret := _m.Called(sourcePath, settings, wr)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}, io.Writer) error); ok {
		r0 = rf(sourcePath, settings, wr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ParseAndExecutePath provides a mock function with given fields: path, settings
func (_m *Engine) ParseAndExecutePath(path string, settings interface{}) (string, error) {
	ret := _m.Called(path, settings)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, interface{}) string); ok {
		r0 = rf(path, settings)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, interface{}) error); ok {
		r1 = rf(path, settings)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
