// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import confighelper "github.com/Chris-Greaves/stencil/confighelper"
import mock "github.com/stretchr/testify/mock"

// IOWrapper is an autogenerated mock type for the IOWrapper type
type IOWrapper struct {
	mock.Mock
}

// GetOverrides provides a mock function with given fields: allSettings
func (_m *IOWrapper) GetOverrides(allSettings []confighelper.Setting) ([]confighelper.Setting, error) {
	ret := _m.Called(allSettings)

	var r0 []confighelper.Setting
	if rf, ok := ret.Get(0).(func([]confighelper.Setting) []confighelper.Setting); ok {
		r0 = rf(allSettings)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]confighelper.Setting)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]confighelper.Setting) error); ok {
		r1 = rf(allSettings)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
