project_name: stencil
release:
  github:
    owner: Chris-Greaves
    name: stencil
  name_template: '{{.Tag}}'
milestones:
- repo:
    owner: Chris-Greaves
    name: stencil
  name_template: '{{ .Tag }}'
scoop:
  name: stencil
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  commit_msg_template: Scoop update for {{ .ProjectName }} version {{ .Tag }}
builds:
- id: stencil
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  - "386"
  goarm:
  - "6"
  gomips:
  - hardfloat
  targets:
  - linux_amd64
  - linux_arm64
  - linux_386
  - darwin_amd64
  - darwin_arm64
  - windows_amd64
  - windows_arm
  - windows_386
  dir: .
  main: .
  ldflags:
  - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    -X main.builtBy=goreleaser
  binary: stencil
  lang: go
  gobinary: go
archives:
- id: default
  builds:
  - stencil
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
  format: tar.gz
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
  allow_different_binary_count: false
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT-{{ .ShortCommit }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256
dist: dist
env_files:
  github_token: ~/.config/goreleaser/github_token
  gitlab_token: ~/.config/goreleaser/gitlab_token
  gitea_token: ~/.config/goreleaser/gitea_token
source:
  name_template: '{{ .ProjectName }}-{{ .Version }}'
  format: tar.gz
gomod:
  gobinary: go
announce:
  twitter:
    message_template: '{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .GitURL
      }}/releases/tag/{{ .Tag }}'
github_urls:
  download: https://github.com
gitlab_urls:
  download: https://gitlab.com
