metadata:
  name: Basic Example
  description: A basic Stencil template example.
vars:
  prompt:
    project_name:
      type: string
      description: The name of your project
      suggestions:
        - MyProject
        - Project.Name
      required: true
    test.name: # Does not work, as the period "." is not allowed in variable names. Use "test_name" instead.
      type: select(string)
      description: The type of project to create
      options:
        - Web
        - API
        - Service
      default: API # Ignored on select prompts, the default value is always the first option
      required: true
    file_name:
      type: string
      description: The name of the file to create
      default: "README"
  static:
    content: "{{ .project_name }} contains a file called {{ .test.name }}.txt"
