// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.


// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"os"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFsWrapper creates a new instance of MockFsWrapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFsWrapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFsWrapper {
	mock := &MockFsWrapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFsWrapper is an autogenerated mock type for the FsWrapper type
type MockFsWrapper struct {
	mock.Mock
}

type MockFsWrapper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFsWrapper) EXPECT() *MockFsWrapper_Expecter {
	return &MockFsWrapper_Expecter{mock: &_m.Mock}
}

// GetHomeDirectory provides a mock function for the type MockFsWrapper
func (_mock *MockFsWrapper) GetHomeDirectory() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHomeDirectory")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFsWrapper_GetHomeDirectory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHomeDirectory'
type MockFsWrapper_GetHomeDirectory_Call struct {
	*mock.Call
}

// GetHomeDirectory is a helper method to define mock.On call
func (_e *MockFsWrapper_Expecter) GetHomeDirectory() *MockFsWrapper_GetHomeDirectory_Call {
	return &MockFsWrapper_GetHomeDirectory_Call{Call: _e.mock.On("GetHomeDirectory")}
}

func (_c *MockFsWrapper_GetHomeDirectory_Call) Run(run func()) *MockFsWrapper_GetHomeDirectory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFsWrapper_GetHomeDirectory_Call) Return(s string, err error) *MockFsWrapper_GetHomeDirectory_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFsWrapper_GetHomeDirectory_Call) RunAndReturn(run func() (string, error)) *MockFsWrapper_GetHomeDirectory_Call {
	_c.Call.Return(run)
	return _c
}

// Lstat provides a mock function for the type MockFsWrapper
func (_mock *MockFsWrapper) Lstat(name string) (os.FileInfo, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Lstat")
	}

	var r0 os.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (os.FileInfo, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) os.FileInfo); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(os.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFsWrapper_Lstat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lstat'
type MockFsWrapper_Lstat_Call struct {
	*mock.Call
}

// Lstat is a helper method to define mock.On call
//   - name string
func (_e *MockFsWrapper_Expecter) Lstat(name interface{}) *MockFsWrapper_Lstat_Call {
	return &MockFsWrapper_Lstat_Call{Call: _e.mock.On("Lstat", name)}
}

func (_c *MockFsWrapper_Lstat_Call) Run(run func(name string)) *MockFsWrapper_Lstat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFsWrapper_Lstat_Call) Return(v os.FileInfo, err error) *MockFsWrapper_Lstat_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockFsWrapper_Lstat_Call) RunAndReturn(run func(name string) (os.FileInfo, error)) *MockFsWrapper_Lstat_Call {
	_c.Call.Return(run)
	return _c
}

// MkdirAll provides a mock function for the type MockFsWrapper
func (_mock *MockFsWrapper) MkdirAll(path string, perm os.FileMode) error {
	ret := _mock.Called(path, perm)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, os.FileMode) error); ok {
		r0 = returnFunc(path, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFsWrapper_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type MockFsWrapper_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path string
//   - perm os.FileMode
func (_e *MockFsWrapper_Expecter) MkdirAll(path interface{}, perm interface{}) *MockFsWrapper_MkdirAll_Call {
	return &MockFsWrapper_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path, perm)}
}

func (_c *MockFsWrapper_MkdirAll_Call) Run(run func(path string, perm os.FileMode)) *MockFsWrapper_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 os.FileMode
		if args[1] != nil {
			arg1 = args[1].(os.FileMode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFsWrapper_MkdirAll_Call) Return(err error) *MockFsWrapper_MkdirAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFsWrapper_MkdirAll_Call) RunAndReturn(run func(path string, perm os.FileMode) error) *MockFsWrapper_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function for the type MockFsWrapper
func (_mock *MockFsWrapper) ReadFile(name string) ([]byte, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFsWrapper_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockFsWrapper_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - name string
func (_e *MockFsWrapper_Expecter) ReadFile(name interface{}) *MockFsWrapper_ReadFile_Call {
	return &MockFsWrapper_ReadFile_Call{Call: _e.mock.On("ReadFile", name)}
}

func (_c *MockFsWrapper_ReadFile_Call) Run(run func(name string)) *MockFsWrapper_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFsWrapper_ReadFile_Call) Return(bytes []byte, err error) *MockFsWrapper_ReadFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockFsWrapper_ReadFile_Call) RunAndReturn(run func(name string) ([]byte, error)) *MockFsWrapper_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function for the type MockFsWrapper
func (_mock *MockFsWrapper) WriteFile(name string, data []byte, perm os.FileMode) error {
	ret := _mock.Called(name, data, perm)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, os.FileMode) error); ok {
		r0 = returnFunc(name, data, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFsWrapper_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockFsWrapper_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - name string
//   - data []byte
//   - perm os.FileMode
func (_e *MockFsWrapper_Expecter) WriteFile(name interface{}, data interface{}, perm interface{}) *MockFsWrapper_WriteFile_Call {
	return &MockFsWrapper_WriteFile_Call{Call: _e.mock.On("WriteFile", name, data, perm)}
}

func (_c *MockFsWrapper_WriteFile_Call) Run(run func(name string, data []byte, perm os.FileMode)) *MockFsWrapper_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 os.FileMode
		if args[2] != nil {
			arg2 = args[2].(os.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFsWrapper_WriteFile_Call) Return(err error) *MockFsWrapper_WriteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFsWrapper_WriteFile_Call) RunAndReturn(run func(name string, data []byte, perm os.FileMode) error) *MockFsWrapper_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}
