// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockGitRunner creates a new instance of MockGitRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitRunner {
	mock := &MockGitRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGitRunner is an autogenerated mock type for the GitRunner type
type MockGitRunner struct {
	mock.Mock
}

type MockGitRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitRunner) EXPECT() *MockGitRunner_Expecter {
	return &MockGitRunner_Expecter{mock: &_m.Mock}
}

// AddRemote provides a mock function for the type MockGitRunner
func (_mock *MockGitRunner) AddRemote(dir string, name string, url string) error {
	ret := _mock.Called(dir, name, url)

	if len(ret) == 0 {
		panic("no return value specified for AddRemote")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(dir, name, url)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitRunner_AddRemote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRemote'
type MockGitRunner_AddRemote_Call struct {
	*mock.Call
}

// AddRemote is a helper method to define mock.On call
//   - dir string
//   - name string
//   - url string
func (_e *MockGitRunner_Expecter) AddRemote(dir interface{}, name interface{}, url interface{}) *MockGitRunner_AddRemote_Call {
	return &MockGitRunner_AddRemote_Call{Call: _e.mock.On("AddRemote", dir, name, url)}
}

func (_c *MockGitRunner_AddRemote_Call) Run(run func(dir string, name string, url string)) *MockGitRunner_AddRemote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGitRunner_AddRemote_Call) Return(err error) *MockGitRunner_AddRemote_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitRunner_AddRemote_Call) RunAndReturn(run func(dir string, name string, url string) error) *MockGitRunner_AddRemote_Call {
	_c.Call.Return(run)
	return _c
}

// FetchRemote provides a mock function for the type MockGitRunner
func (_mock *MockGitRunner) FetchRemote(dir string, remote string) error {
	ret := _mock.Called(dir, remote)

	if len(ret) == 0 {
		panic("no return value specified for FetchRemote")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(dir, remote)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitRunner_FetchRemote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchRemote'
type MockGitRunner_FetchRemote_Call struct {
	*mock.Call
}

// FetchRemote is a helper method to define mock.On call
//   - dir string
//   - remote string
func (_e *MockGitRunner_Expecter) FetchRemote(dir interface{}, remote interface{}) *MockGitRunner_FetchRemote_Call {
	return &MockGitRunner_FetchRemote_Call{Call: _e.mock.On("FetchRemote", dir, remote)}
}

func (_c *MockGitRunner_FetchRemote_Call) Run(run func(dir string, remote string)) *MockGitRunner_FetchRemote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitRunner_FetchRemote_Call) Return(err error) *MockGitRunner_FetchRemote_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitRunner_FetchRemote_Call) RunAndReturn(run func(dir string, remote string) error) *MockGitRunner_FetchRemote_Call {
	_c.Call.Return(run)
	return _c
}

// Initialize provides a mock function for the type MockGitRunner
func (_mock *MockGitRunner) Initialize(dir string) error {
	ret := _mock.Called(dir)

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(dir)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitRunner_Initialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initialize'
type MockGitRunner_Initialize_Call struct {
	*mock.Call
}

// Initialize is a helper method to define mock.On call
//   - dir string
func (_e *MockGitRunner_Expecter) Initialize(dir interface{}) *MockGitRunner_Initialize_Call {
	return &MockGitRunner_Initialize_Call{Call: _e.mock.On("Initialize", dir)}
}

func (_c *MockGitRunner_Initialize_Call) Run(run func(dir string)) *MockGitRunner_Initialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGitRunner_Initialize_Call) Return(err error) *MockGitRunner_Initialize_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitRunner_Initialize_Call) RunAndReturn(run func(dir string) error) *MockGitRunner_Initialize_Call {
	_c.Call.Return(run)
	return _c
}

// PullRemote provides a mock function for the type MockGitRunner
func (_mock *MockGitRunner) PullRemote(dir string, remote string, branch string) error {
	ret := _mock.Called(dir, remote, branch)

	if len(ret) == 0 {
		panic("no return value specified for PullRemote")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(dir, remote, branch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitRunner_PullRemote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullRemote'
type MockGitRunner_PullRemote_Call struct {
	*mock.Call
}

// PullRemote is a helper method to define mock.On call
//   - dir string
//   - remote string
//   - branch string
func (_e *MockGitRunner_Expecter) PullRemote(dir interface{}, remote interface{}, branch interface{}) *MockGitRunner_PullRemote_Call {
	return &MockGitRunner_PullRemote_Call{Call: _e.mock.On("PullRemote", dir, remote, branch)}
}

func (_c *MockGitRunner_PullRemote_Call) Run(run func(dir string, remote string, branch string)) *MockGitRunner_PullRemote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGitRunner_PullRemote_Call) Return(err error) *MockGitRunner_PullRemote_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitRunner_PullRemote_Call) RunAndReturn(run func(dir string, remote string, branch string) error) *MockGitRunner_PullRemote_Call {
	_c.Call.Return(run)
	return _c
}
