// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockExecutor creates a new instance of MockExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutor {
	mock := &MockExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExecutor is an autogenerated mock type for the Executor type
type MockExecutor struct {
	mock.Mock
}

type MockExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecutor) EXPECT() *MockExecutor_Expecter {
	return &MockExecutor_Expecter{mock: &_m.Mock}
}

// CheckPathForExecutable provides a mock function for the type MockExecutor
func (_mock *MockExecutor) CheckPathForExecutable(file string) (string, error) {
	ret := _mock.Called(file)

	if len(ret) == 0 {
		panic("no return value specified for CheckPathForExecutable")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(file)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(file)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(file)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExecutor_CheckPathForExecutable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPathForExecutable'
type MockExecutor_CheckPathForExecutable_Call struct {
	*mock.Call
}

// CheckPathForExecutable is a helper method to define mock.On call
//   - file string
func (_e *MockExecutor_Expecter) CheckPathForExecutable(file interface{}) *MockExecutor_CheckPathForExecutable_Call {
	return &MockExecutor_CheckPathForExecutable_Call{Call: _e.mock.On("CheckPathForExecutable", file)}
}

func (_c *MockExecutor_CheckPathForExecutable_Call) Run(run func(file string)) *MockExecutor_CheckPathForExecutable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExecutor_CheckPathForExecutable_Call) Return(s string, err error) *MockExecutor_CheckPathForExecutable_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockExecutor_CheckPathForExecutable_Call) RunAndReturn(run func(file string) (string, error)) *MockExecutor_CheckPathForExecutable_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteCommandInDir provides a mock function for the type MockExecutor
func (_mock *MockExecutor) ExecuteCommandInDir(path string, name string, args ...string) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(path, name, args)
	} else {
		tmpRet = _mock.Called(path, name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ExecuteCommandInDir")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, ...string) error); ok {
		r0 = returnFunc(path, name, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExecutor_ExecuteCommandInDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteCommandInDir'
type MockExecutor_ExecuteCommandInDir_Call struct {
	*mock.Call
}

// ExecuteCommandInDir is a helper method to define mock.On call
//   - path string
//   - name string
//   - args ...string
func (_e *MockExecutor_Expecter) ExecuteCommandInDir(path interface{}, name interface{}, args ...interface{}) *MockExecutor_ExecuteCommandInDir_Call {
	return &MockExecutor_ExecuteCommandInDir_Call{Call: _e.mock.On("ExecuteCommandInDir",
		append([]interface{}{path, name}, args...)...)}
}

func (_c *MockExecutor_ExecuteCommandInDir_Call) Run(run func(path string, name string, args ...string)) *MockExecutor_ExecuteCommandInDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockExecutor_ExecuteCommandInDir_Call) Return(err error) *MockExecutor_ExecuteCommandInDir_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExecutor_ExecuteCommandInDir_Call) RunAndReturn(run func(path string, name string, args ...string) error) *MockExecutor_ExecuteCommandInDir_Call {
	_c.Call.Return(run)
	return _c
}
