name: Release

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build for environments 
      env:
        VERSION: ${{ github.ref }}
      run: .github/workflows/scripts/go-build-all.sh
    
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "bin/*.tar.gz,bin/*.zip"
        #bodyFile: "body.md" # Look into using this with https://github.com/haunt98/changeloguru
        token: ${{ secrets.GITHUB_TOKEN }}
